Repository appuio/component-openshift4-console, pull requests merged in 2023-07, with the labels that each got.

#58 Remove support for OpenShift <= 4.7
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/custom-route-4.7/openshift4-console/apps/openshift4-console.yaml
  tests/golden/custom-route-legacy-4.7/openshift4-console/apps/openshift4-console.yaml
Labels: breaking

#59 Remove left-over OCP 4.7 test cases
  tests/custom-route-4.7.yml
  tests/custom-route-legacy-4.7.yml
  tests/golden/custom-route-4.7/openshift4-console/openshift4-console/00_namespace.yaml
  tests/golden/custom-route-4.7/openshift4-console/openshift4-console/10_console.yaml
  tests/golden/custom-route-legacy-4.7/openshift4-console/openshift4-console/00_namespace.yaml
  tests/golden/custom-route-legacy-4.7/openshift4-console/openshift4-console/10_console.yaml
Labels: ignore

#60 Use `patch-operator.libsonnet` directly
  component/main.jsonnet
  tests/custom-logo.yml
  tests/custom-route-legacy.yml
  tests/custom-route-managed-tls.yml
  tests/custom-route.yml
  tests/golden/custom-logo/openshift4-console/openshift4-console/20_ingress_config_patch.yaml
  tests/golden/custom-route-legacy/openshift4-console/openshift4-console/20_ingress_config_patch.yaml
  tests/golden/custom-route-managed-tls/openshift4-console/openshift4-console/20_ingress_config_patch.yaml
  tests/golden/custom-route-managed-tls/openshift4-console/openshift4-console/20_openshift_config_ns_annotation_patch.yaml
  tests/golden/custom-route/openshift4-console/openshift4-console/20_ingress_config_patch.yaml
Labels: change
